### PR TITLE
yl/mb - 6pm-3 - Login Admin Table Sortable

### PR DESCRIPTION
**Pull request by YuehanLee**
Before:
The Login admin table is not sortable.
After:
It can be sorted if you click one of the label on the top.

### CODE REVIEW

**Review by m-cabello — APPROVED** [review]
Looks like you followed the instructions well and accurately. LGTM

**Review by pconrad — CHANGES_REQUESTED** [review]
The PR description here describes "problems".  That's ok in an issue description.  But in a PR description, you need to describe what is *now fixed*, not what *was broken*.

Something more like:

> In this PR, we fix a problem with sorting.  Before, such and such bad thing was happening. Now such and such good thing is happening.

It can be helpful to include a before / after screenshot.

**Review by cliffordxu — APPROVED** [review]
LGTM

**Review by WadeVaresio — APPROVED** [review]
LGTM

**Pull request merged**
