### PR TITLE
rt - 6pm-2 Use Bootstrap classes for styling on Admin/View Logins page and Tutor Assignments button

### PR DESCRIPTION
**Pull request by rowantran**
Stored the button on the Tutor Assignments page as a variable to avoid duplicating the markup for it.
Also replaced the hardcoded `style` attributes with the appropriate Bootstrap utility classes in the following locations:
1. Header on the Admin/View Logins page
2. Button on the Tutor Assignments page

### CODE REVIEW

**Review by pconrad — APPROVED** [review]
LGTM..  I'm authorizing this to be merged in spite of the codecov issue...  it's minor and there's no change here that should trigger a need for more tests.

We should test it interactively first though before merging.

**Review by pconrad — CHANGES_REQUESTED** [review]
Title and description of PR should reflect that it is changing both the `Admin/View Logins` page and the button on the Tutor assignments page.

This is important so that we know what pages to look at when testing.

**Review by RaghubirChimni — APPROVED** [review]
LGTM.

**Review by noahcorona44 — APPROVED** [review]
LGTM

**Review by arunryu — APPROVED** [review]
LGTM

**Comment by Wilson-Flan** [comment]
LGTM

**Review by Wilson-Flan — APPROVED** [review]
LGTM

**Review by JacquelineMai — CHANGES_REQUESTED** [review]
These code changes look good, but it looks like the linked issue also specifies that you should add a description to the Login History page. This should just be a short text description about what the info on the page represents- i.e. a list of all the log-ins on the app.

**Comment by rowantran** [comment]
> 
> 
> These code changes look good, but it looks like the linked issue also specifies that you should add a description to the Login History page. This should just be a short text description about what the info on the page represents- i.e. a list of all the log-ins on the app.

Sorry, the user story and acceptance criteria that I copied from the original issue do seem to imply that, but the implementation todos in #190 suggest that the "description" in question is just the page header. It should be a quick change either way, but do you think an actual text description is still necessary?

**Comment by JacquelineMai** [comment]
> 
> 
> > These code changes look good, but it looks like the linked issue also specifies that you should add a description to the Login History page. This should just be a short text description about what the info on the page represents- i.e. a list of all the log-ins on the app.
> 
> Sorry, the user story and acceptance criteria that I copied from the original issue do seem to imply that, but the implementation todos in #190 suggest that the "description" in question is just the page header. It should be a quick change either way, but do you think an actual text description is still necessary?

Looking at the todos, I think you're right that this should be sufficient

**Review by JacquelineMai — APPROVED** [review]
lgtm

**Pull request merged**
