### PR TITLE
cx 6pm-1 Add Instruction to Quarter Filter

### PR DESCRIPTION
**Pull request by PureDreamerGk**
In this PR, we added some instruction to Quarter Filter page so the user know what the page is for.

### CODE REVIEW

**Review by kenny-wang6 — APPROVED** [review]
LGTM

**Review by omarbuzdar — APPROVED** [review]
This looks good to me.

**Comment by pconrad** [comment]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
