### PR TITLE
nc/ar - 6pm-2 add header to view logins subpage

### PR DESCRIPTION
**Pull request by noahcorona44**
Header reads 'Login History'

### CODE REVIEW

**Review by RaghubirChimni — APPROVED** [review]
LGTM

**Review by RaghubirChimni — DISMISSED** [review]
LGTM

**Review by JacquelineMai — CHANGES_REQUESTED** [review]
Please don't remove the SAMPLE files. They're intended to remain in the repo so anyone who clones it in the future has the proper templates for the configuration files. I can approve this PR once you undo the deletion of `javascript/.env.local.SAMPLE`- feel free to ask the staff if you need help with this :)

**Review by JacquelineMai — APPROVED** [review]

**Review by rowantran — APPROVED** [review]
LGTM

**Pull request merged**
