### PR TITLE
6pm-1 CX/KW -user couldn't edit tutor name when they update office hour

### PR DESCRIPTION
**Pull request by PureDreamerGk**
In this PR, we update the office hour form so that the user will not be able to edit the tutor when they update the office hour.

### CODE REVIEW

**Comment by PureDreamerGk** [comment]
We need to add a test on TutorDisplay component

**Review by JacquelineMai — DISMISSED** [review]
I believe for this issue, we want you to remove the editable part of the form pertaining to the tutor altogether on the edit page, and only use the TutorAssignmentSelector when creating a new assignment. In this current state of this branch, it looks like the selector still exists, and the tutor's name is displayed in text below it.:
image

We only want the text displayed, so that when editing an office hour we cannot edit the tutor assigned to that hour.

**Comment by kenny-wang6** [comment]
> I believe for this issue, we want you to remove the editable part of the form pertaining to the tutor altogether on the edit page, and only use the TutorAssignmentSelector when creating a new assignment. In this current state of this branch, it looks like the selector still exists, and the tutor's name is displayed in text below it.:
> image
> 
> We only want the text displayed, so that when editing an office hour we cannot edit the tutor assigned to that hour.

My bad, I ended up fixing the tests but didn't realize the implementation had bugs after changing the code. Will work on fixing both issues now.

**Review by pconrad — APPROVED** [review]
LGTM

**Comment by pconrad** [comment]
This is good for 10 points when merged.

**Review by wongjulian4213 — APPROVED** [review]
Looks good to me!

**Pull request merged**
