### PR TITLE
mc/zw/an-6pm 3 tutor notes database implementation

### PR DESCRIPTION
**Pull request by m-cabello**
Implemented a tutor notes database and columns exist for course, author/uploader, and the notes.

### CODE REVIEW

**Review by pconrad — APPROVED** [review]
LGTM.   You still need a member of the team to review this too.

**Comment by pconrad** [comment]
Estimate this at 10 points

**Review by YuehanLee — COMMENTED** [review]
LGTM, good works

**Comment by pconrad** [comment]
> LGTM, good works

This is a comment, not a code review.  Please do a code review.

**Review by pconrad — CHANGES_REQUESTED** [review]
This needs a PR description before it can be merged

**Review by YuehanLee — APPROVED** [review]
LGTM, good works!

**Review by pconrad — APPROVED** [review]

**Pull request merged**
